Repository vignetteapp/vignette-web, pull requests merged in 2021-10, with the labels that each got.

#3 feat: sidebar
  package.json
  src/components/icons/logo.tsx
  src/components/sections/about.tsx
  src/components/sections/home.tsx
  src/components/sidebar/index.tsx
  src/components/sidebar/link.tsx
  src/pages/index.tsx
  src/styles/main.css
  tailwind.config.js
  yarn.lock
Labels: hacktoberfest

#11 Remove commit linting
  .husky/commit-msg
  .husky/common.sh
  .husky/pre-commit
  package.json
  yarn.lock
Labels: enhancement

#13 Update README and LICENSE
  CODE_OF_CONDUCT.md
  LICENSE.md
  README.md
Labels: documentation

#17 Update expired Discord invite
  src/components/sidebar/index.tsx
Labels: hacktoberfest

#20 tweak responsive design
  src/components/footer.tsx
  src/components/sections/about.tsx
  src/components/sections/features.tsx
  src/components/sections/home.tsx
Labels: hacktoberfest

#23 feat(sidebar): highlight link when scroll
  src/components/sidebar/index.tsx
  src/utils/navigate.ts
Labels: enhancement, hacktoberfest

#24 feat(sidebar): add animation on view
  public/images/profiles/ayane.jpg
  src/components/footer.tsx
  src/components/icons/logo.tsx
  src/components/sidebar/index.tsx
  src/components/sidebar/link.tsx
  src/pages/_document.tsx
  src/utils/arrayify.ts
  src/utils/hide.ts
  src/utils/show.ts
Labels: enhancement
